openapi: 3.0.1
info:
    title: Location-based Restaurant Recommendation
    description: Get top restaurant recommendations based on the user's location.
    version: "1.0.0"
servers:
    - url: "http://localhost:8080"
paths:
    /Recommend:
        get:
            operationId: getRecommendation
            summary: Gets top restaurant recommendations based on the user's address.
            parameters:
                - in: query
                  name: user_address
                  schema:
                      type: string
                  description: The address of the user to find nearby restaurants.
            responses:
                "200":
                    description: Successfully fetched top restaurant recommendations.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                                        address:
                                            type: string
                                        latitude:
                                            type: number
                                        longitude:
                                            type: number
                                        distance:
                                            type: number
                "400":
                    description: Bad request. Required parameters are missing or invalid.
